name: Deploy to Hugging Face

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://oauth2:$HF_TOKEN@huggingface.co/spaces/hamza-11/MMA_Tier hf-space

          rsync -av --exclude='.git' ./ hf-space/

          cd hf-space

          git add .

          git commit -m "Auto deploy from GitHub Actions" || echo "No changes"

          git push